name: CI
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/**"
  push:
    branches: [ "main" ]

jobs:
  frontend:
    name: Frontend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run build
      # - run: npm test   # enable when tests exist

  backend:
    name: Backend install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      # - run: npm run build || echo "no backend build script"  # optional
      # - run: npm test  # enable when tests exist
